# all commands by default will run on every push, not every commit
default_install_hook_types: [pre-push]
default_stages: [push]

# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'

repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.11.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-snowflake==1.0.0',
          'sqlfluff-templater-dbt==0.11.2'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-snowflake==1.0.0',
          'sqlfluff-templater-dbt==0.11.2'
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
