repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.5.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['.[dbt]']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
