# These are base configs for dbt.
# You probably won't need to change these!
name: 'poutine_shop'
version: '1.0.0'
config-version: 2
profile: 'poutine_shop'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

# Require dbt 0.19.x
require-dbt-version: [">=0.20.0", "<0.21.0"]

# ==================
# Model Configs
# ==================

models:
  poutine_shop:
    # marts:
    #     core:
    #         +materialized: table
    staging:
        +materialized: view
