# These are base configs for dbt.
# You probably won't need to change these!
name: 'poutine_shop'
version: '1.0.0'
config-version: 2
profile: 'poutine_shop'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

# Add a dynamic query comment providing context of execution
query-comment:
  comment: "{{ query_comment(node) }}"
  append: true

# Require dbt 0.19.x
require-dbt-version: [">=1.0.0", "<1.1.0"]

# Variables
vars:
  util_days_start_date: "1970-01-01"

  dbt_artifacts:
    dbt_artifacts_database: poutineshop_dbt_artifacts_db
    dbt_artifacts_schema: dbt_artifacts
    dbt_artifacts_table: artifacts
    dbt_artifacts_results_table: dbt_run_results
    dbt_artifacts_result_nodes_table: dbt_run_result_nodes
    dbt_artifacts_manifest_nodes_table: dbt_manifest_nodes

# Models
models:
  poutine_shop:
    marts:
      # Default materialization of marts should be tables
      +materialized: table

    staging:
      # Default materialization of staging should be views
      +materialized: view

    utils:
      # Default materialization of utils should be tables
      +materialized: table

  dbt_artifacts:
    +schema: dbt_artifacts
    staging:
      +schema: dbt_artifacts
