# These are base configs for dbt.
# You probably won't need to change these!
name: 'poutine_shop'
version: '1.0.0'
config-version: 2
profile: 'poutine_shop'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
packages-install-path: "dbt_packages"
clean-targets: ["target", "dbt_packages"]

# Add a dynamic query comment providing context of execution
query-comment:
  comment: "{{ query_comment(node) }}"
  append: true

# Require dbt 1.0.0+
require-dbt-version: [">=1.0.0", "<=1.1.0"]

# Variables
vars:
  util_days_start_date: "1970-01-01"

# Hooks
on-run-end:
  # Grant usage to both our Looker and Sigma instances
  - "{{ grant_usage_on_schemas(schemas, 'LOOKER_ROLE') }}"
  - "{{ grant_usage_on_schemas(schemas, 'SIGMA_ROLE') }}"

# Models
models:
  poutine_shop:
    marts:
      # Default materialization of marts should be tables
      +materialized: table

      # Grant select to both our Looker and Sigma instances
      +post-hook:
        - "{{ grant_select('SIGMA_ROLE') }}"
        - "{{ grant_select('LOOKER_ROLE') }}"

      core:
        +schema: core

    staging:
      # Default materialization of staging should be views
      +materialized: view

    utils:
      # Default materialization of utils should be tables
      +materialized: table
