# These are base configs for dbt.
# You probably won't need to change these!
name: 'poutine_shop'
version: '1.0.0'
config-version: 2
profile: 'poutine_shop'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

# Add a dynamic query comment providing context of execution
query-comment:
  comment: "{{ query_comment(node) }}"
  append: true

# Require dbt 0.19.x
require-dbt-version: [">=0.20.0", "<0.21.0"]

# Variables
vars:
  util_days_start_date: "1970-01-01"

# Models
models:
  poutine_shop:
    marts:
      # Default materialization of marts should be tables
      +materialized: table

    staging:
      # Default materialization of staging should be views
      +materialized: view

    utils:
      # Default materialization of utils should be tables
      +materialized: table
