name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  sqlfluff-lint-files:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: .ci/

      # Declare all environment variables needed in profiles.yml
      PROFILES_YML_SNOWFLAKE_ACCOUNT: ${{secrets.SNOWFLAKE_ACCOUNT_ID}}
      PROFILES_YML_SNOWFLAKE_USER: ${{secrets.SNOWFLAKE_CI_SERVICE_ACCOUNT_USERNAME}}
      PROFILES_YML_SNOWFLAKE_PASSWORD: ${{secrets.SNOWFLAKE_CI_SERVICE_ACCOUNT_PASSWORD}}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dbt and sqlfluff
        run: |
          pip install dbt-snowflake==1.2.0 \
          sqlfluff==1.2.1 \
          sqlfluff-templater-dbt==1.2.1

      - name: Install dbt Packages
        run: dbt deps

      - run: git checkout ${{steps.comment-branch.outputs.head_ref}}

      - run: pwd

      - run: ls -a

      - name: Lint SQL files
        run: |
          diff-quality --violations sqlfluff \
          --compare-branch remotes/origin/main \
          --config-file .sqlfluff

  yamllint-lint-files:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          # this can be changed if you have .yml files in other directorie
          yamllint_file_or_dir: 'models/'
          yamllint_strict: false
