name: pre-commit

on:
  pull_request:
  push:
    branches: main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - run: echo ${{ steps.file_changes.outputs.files}}
      - uses: Montreal-Analytics/dbt-gloss@main
        env:
          DB_PASSWORD: ${{ secrets.SuperSecret }}
        with:
          args: --entrypoint "pre-commit" run --files ${{ steps.file_changes.outputs.files}}
